### ISSUE TITLE
Add a tip under `lineLengthLimit` to explain the default 500 character value

### ISSUE THREAD

**Issue by jkupczak** [cossssmin/alter.email#3]
I don't think most people are aware of the restrictions related to line length in emails. To most, the 500 default value may seem arbitrary. Some short help text here and a link to a longer explanation would be a great idea I think.

**Comment by cossssmin** [comment]
Good call, how does this sound?

> While a line of code can be up to [998 characters](https://tools.ietf.org/html/rfc5322#section-2.1.1) long, some email clients require even less. A conservative `500` is usually recommended for HTML emails.

**Comment by jkupczak** [comment]
That's perfect.
