### ISSUE TITLE
Remember last used settings

### ISSUE THREAD

**Issue by jkupczak** [cossssmin/alter.email#5]
I think more people would be inclined to make this part of their workflow if they could come back to the site days later and have all of their preferred toggles pre-populated. I'm thinking the UI could use a one or a couple of switches for...

- Use previous settings
- Clear all settings/Start from scratch

Probably save their settings to localStorage whenever they hit the "Alter Email" button.

This could snowball into offering an interface to save multiple different "profiles" of settings for people that have different needs based on the kind of email they're sending that day.

**Comment by cossssmin** [comment]
I like the idea, let me see what I can come up with.
