### ISSUE TITLE
URL Parameters function encodes spaces as `%20` instead of `+`

### ISSUE THREAD

**Issue by jkupczak** [cossssmin/alter.email#7]
As I understand it, the generally accepted method of encoding spaces in URL parameters is to convert them to a `+`. At the moment, alter.email encodes spaces as `%20` instead.

See this answer on Stackoverflow for some background:
https://stackoverflow.com/a/29948396/556079

It should also be noted that the URL.searchParams API uses `+` instead of `%20`:
https://developer.mozilla.org/en-US/docs/Web/API/URL/searchParams

I haven't taken the time to check **how** you're encoding the parameters. If it's not relying on someone else's library then I'd recommend a change. Otherwise I suppose this is an issue for another repo.

**Comment by cossssmin** [comment]
OK, I think we can go with this then?

```js
const alterEncodeURIComponent = (str) => {
  encodeURIComponent(str)
    .replace(/[!'()*]/g, (c) => '%' + c.charCodeAt(0).toString(16))
    .replace(/%20/g, '+')
}
```

```js
alterEncodeURIComponent('This is + my string!')
// "This+is+%2B+my+string%21"
```
